import { chromium } from "playwright-core";
import fs from "node:fs/promises";
import path from "node:path";

const root = path.resolve(process.cwd());
const out = path.join(root, "artifacts/demo");
const locale = process.env.DEMO_LOCALE === "zh" ? "zh" : "en";
const suffix = locale === "zh" ? "-zh" : "";
const speed = locale === "zh" ? 1.5 : 2;
const cast = await fs.readFile(path.join(out, `pi-debug-mode-real-tui${suffix}.compact.cast`), "utf8");
const lines = cast.trim().split("\n");
const duration = JSON.parse(lines.at(-1))[0] / speed;
const browser = await chromium.launch({ headless: true, executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" });
const context = await browser.newContext({ viewport: { width: 1280, height: 720 }, recordVideo: { dir: out, size: { width: 1280, height: 720 } } });
const page = await context.newPage();
const playerPage = locale === "zh" ? "player-zh.html" : "player.html";
await page.goto(`http://127.0.0.1:41732/tools/real-tui-video/${playerPage}`, { waitUntil: "networkidle" });
await page.waitForSelector(".ap-player");
await page.waitForTimeout(1000);
await page.screenshot({ path: path.join(out, `pi-debug-mode-real-tui${suffix}-poster.png`) });
await page.waitForTimeout((duration + 3) * 1000);
const video = page.video();
const originalVideo = await video.path();
const stableVideo = path.join(out, `pi-debug-mode-real-tui${suffix}.webm`);
await context.close();
await video.saveAs(stableVideo);
if (originalVideo !== stableVideo) await fs.rm(originalVideo, { force: true });
await browser.close();
console.log(JSON.stringify({ ok: true, playbackSeconds: duration }));
